### ISSUE TITLE
Compatibility with *.fad files Yomawari MS - PSVita

### ISSUE THREAD

**Issue by Akatsukidarkx** [blackwaterbread/poro#1]
Hi, would it be possible to implement compatibility with the *.fad files of Yomawari MS for PSVita?

When extracting *.fad files to *.png files most of them don't look good, I guess it's because of the swizzle, although I have no idea how to implement it.

[https://i.postimg.cc/0N5wd8cp/img-000-0000000000000000-8-256-ykcmp.png](url)

[https://1drv.ms/u/s!AoMD1Sh58wO582VNDD6yqOd-rPLE?e=NjlZb6](url)

Or if not possible, could some option be added so that the *.fad files extract them as *.ykcmp files without converting to png? 
Since in the latter case, I have a way to manually extract the images using an external tool, which would be this one.

[https://1drv.ms/u/s!AoMD1Sh58wO582YKzUkFjLGrtOTJ?e=DqAjLS](url)

**Comment by blackwaterbread** [comment]
Hello Akatsukidarkx.

As you said, that image seems to have swizzled
can't help you with this issue cause I've stopped working on it now
(And I don't know exactly about this "swizzle" problem)
added raw ykcmp extract option for you (with --raw or -r)

Regards,
blackwaterbread
